// // import { ClerkProvider } from "@clerk/nextjs";
// // import "./globals.css";

// // export default function RootLayout({ children }: { children: React.ReactNode }) {
// //   return (
// //     <html lang="en">
// //       <body>
// //         <ClerkProvider>
// //           {children}
// //         </ClerkProvider>
// //       </body>
// //     </html>
// //   );
// // }


// "use client"; // required to use hooks

// import { ClerkProvider, useUser } from "@clerk/nextjs";
// import { useEffect } from "react";
// import "./globals.css";
// import Header from "../components/Header";

// // Component to save user to backend
// function SaveUserOnLogin() {
//   const { user } = useUser();

//   useEffect(() => {
//     if (!user) return;

//     fetch("http://localhost:5000/api/users/upsert", {
//       method: "POST",
//       headers: { "Content-Type": "application/json" },
//       body: JSON.stringify({
//         id: user.id,
//         email: user.primaryEmailAddress?.emailAddress,
//         name: user.firstName + " " + user.lastName,
//       }),
//     })
//       .then((res) => res.json())
//       .then((data) => console.log("Upsert user result:", data))
//       .catch((err) => console.error("Error upserting user:", err));
//   }, [user]);

//   return null;
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <ClerkProvider>
//           <SaveUserOnLogin /> {/* Add this to auto-save users */}
//           <Header />
//           {children}
//         </ClerkProvider>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
//  import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased">
          <ErrorReporter />
          <Script
            src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
            strategy="afterInteractive"
            data-target-origin="*"
            data-message-type="ROUTE_CHANGE"
            data-include-search-params="true"
            data-only-in-iframe="true"
            data-debug="true"
            data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
          />
          {children}
          {/* <VisualEditsMessenger /> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
